name: 'Composite Action'
description: 'Testing composite action'
inputs:
  name:
    description: 'Your name'
    default: John Doe
outputs:
  the-output:
    description: The output
    value: ${{ steps.bar.outputs.bar_output }}
runs:
  using: composite
  steps:
    - id: foo
      shell: bash
      run: |
        echo "::set-output name=foo_output::hello"
    - shell: bash
      run: |
        echo "$STEPS_CONTEXT"
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
    - id: bar
      shell: bash
      run: |
        echo "::set-output name=bar_output::${{ steps.foo.outputs.foo_output }}"
